version: "3.9"
services:
  zomboid:
    build:
      context: ./
    user: root
    volumes:
      - ./Zomboid:/root/Zomboid
    ports:
      - "8766:8766/udp"
      - "16261:16261/udp"
      - "16262-16272:16262-16272"
    mem_limit: 8G
    mem_reservation: 6G
  backup:
    build:
      context: ./
      dockerfile: backup.dockerfile
    volumes:
      - ./Zomboid:/home/Zomboid
      - ./backups:/home/backups
